-- Atributos + hardening de usuarios

CREATE TABLE IF NOT EXISTS public.atributos_personagem (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  personagem_id bigint REFERENCES public.personagens(id) ON DELETE CASCADE,
  velocidade integer DEFAULT 0,
  taijutsu integer DEFAULT 0,
  ninjutsu integer DEFAULT 0,
  forca integer DEFAULT 0,
  resistencia integer DEFAULT 0,
  genjutsu integer DEFAULT 0,
  selos integer DEFAULT 0,
  inteligencia integer DEFAULT 0,
  fuinjutsu integer DEFAULT 0,
  ningeral integer DEFAULT 0,
  elementos integer DEFAULT 0,
  kenjutsu integer DEFAULT 0,
  shurikenjutsu integer DEFAULT 0,
  combate integer DEFAULT 0
);

-- password_hash passa a aceitar prefixo sha256: (app faz upgrade no login)
ALTER TABLE public.usuarios
  ADD COLUMN IF NOT EXISTS password_hash text,
  ADD COLUMN IF NOT EXISTS notificacoes_habilitadas boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS ativo boolean DEFAULT true;

-- Recarrega cache do PostgREST se colunas forem alteradas
-- NOTIFY pgrst, 'reload schema';
