-- Colunas usadas por Combate / Jornada (idempotente)
ALTER TABLE public.personagens
  ADD COLUMN IF NOT EXISTS missao_s integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS missao_a integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS missao_b integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS missao_c integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS missao_d integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS historico_graduacoes text;

-- Garante tabela de atributos (combate)
CREATE TABLE IF NOT EXISTS public.atributos_personagem (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  personagem_id bigint REFERENCES public.personagens(id) ON DELETE CASCADE,
  velocidade integer DEFAULT 0,
  taijutsu integer DEFAULT 0,
  ninjutsu integer DEFAULT 0,
  forca integer DEFAULT 0,
  resistencia integer DEFAULT 0,
  genjutsu integer DEFAULT 0,
  selos integer DEFAULT 0,
  inteligencia integer DEFAULT 0,
  fuinjutsu integer DEFAULT 0,
  ningeral integer DEFAULT 0,
  elementos integer DEFAULT 0,
  kenjutsu integer DEFAULT 0,
  shurikenjutsu integer DEFAULT 0,
  combate integer DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS atributos_personagem_personagem_id_uidx
  ON public.atributos_personagem (personagem_id);

GRANT SELECT, INSERT, UPDATE ON public.atributos_personagem TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

NOTIFY pgrst, 'reload schema';
